---

- name: Restart net interface
  service:
    name: netif
    state: restarted

- name: Restart routing
  service:
    name: routing
    state: restarted

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started

