---

- name: Restart net interface
  service:
    name: netif
    state: restarted

- name: Restart routing
  service:
    name: routing
    state: restarted

- name: Restart dhclient
  service:
    name: dhclient
    state: restarted
    args: msk0

