---
- hosts: localhost
  gather_facts: no
  roles:
    - { role: install_ansible_pull, become: yes }
    - { role: snapshots, become: yes, name: ansible, source_dir: /home/ansible, dest_dir: /home/snapshots }
    - { role: podman, become: yes }

