---

# Always maintain ansible "pull-mode" to avoid config drift over time
- import_playbook: bootstrap.yml


# Baseline configuration for all my hosts
- hosts: 'all:!localhost'
  become: yes
  roles:
    - users
    - tools


# Gateway, Firewall, NAS, DHCP, DNS, PXE Boot, WebServer, ...
- hosts: homeserver
  become: yes
  roles:
    - home-server

