---

# Always maintain ansible "pull-mode" to avoid config drift over time
- import_playbook: bootstrap.yml


# Baseline configuration for all my hosts
#- hosts: 'all:!localhost'
#  become: yes
#  roles:
#    - users

