---

# Always maintain ansible "pull-mode" to avoid config drift over time
- hosts: 'all:!localhost'
  become: yes
  roles:
    - install_ansible
    - install_ansible_pull

# Baseline configuration for all my hosts
- hosts: 'all:!localhost'
  become: yes
  roles:
    - users

