---

# Always maintain ansible "pull-mode" to avoid config drift over time
- hosts: 'all:!localhost'
  become: yes
  roles:
    - install_ansible
    - install_ansible_pull

# Baseline configuration for all my hosts
- hosts: 'all:!localhost'
  become: yes
  roles:
    - users

- hosts: d3.home.craigjperry.com
  become: yes
  roles:
    - wireguard

- hosts: s1.home.craigjperry.com
  become: yes
  roles:
    - wireguard
    - postgres
    # k3s install via https://github.com/k3s-io/k3s-ansible

