---

# Preserve snapshots of the NAS share dir

- name: Install snapshot script
  copy:
    src: snapshot.sh
    dest: /usr/local/bin/snapshot.sh
    owner: root
    group: root
    mode: a=rx

- name: Ensure snapshot dir exists
  file:
    path: "{{ item.dest_dir }}"
    state: directory
    mode: '0700'
  loop: "{{ snapshots }}"

- name: Install snapshot cron
  cron:
    name: "snapshots-{{ item.name }}"
    state: present
    user: root
    cron_file: snapshots-{{ item.name }}
    special_time: daily
    job: "/usr/local/bin/snapshot.sh {{ item.source_dir }} {{ item.dest_dir }} > $HOME/logs/snapshot-{{ item.name }}.$$.cron.log"
  loop: "{{ snapshots }}"

