---

# TODO: vbotka.freebsd_pf

- name: Configure static IP
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^ifconfig_msk0="
    line: "ifconfig_msk0=\"inet 192.168.1.253 netmask 255.255.255.0\""
  notify:
    - Restart net interface

- name: Configure default route
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^defaultrouter"
    line: "defaultrouter=\"192.168.1.254\""
  notify:
    - Restart routing

