---

# network handlers

- name: Restart net interface
  service:
    name: netif
    state: restarted

- name: Restart routing
  service:
    name: routing
    state: restarted

- name: Restart dhclient
  service:
    name: dhclient
    state: restarted
    args: igb0


# dnsmasq handlers

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted


# pf firewall handlers

- name: Start pf
  service:
    name: pf
    state: started

- name: Restart pf
  service:
    name: pf
    state: restarted

- name: Start pflog
  service:
    name: pflog
    state: started


# nginx handlers

- name: Restart nginx
  service:
    name: nginx
    state: restarted

# samba handlers

- name: Load AIO
  command: kldload aio

- name: Restart samba
  service:
    name: samba_server
    state: restarted

# nfs handlers

- name: Restart rpcbind
  service:
    name: rpcbind
    state: restarted

- name: Restart rpcstatd
  service:
    name: statd
    state: restarted

- name: Restart mountd
  service:
    name: mountd
    state: restarted

- name: Restart nfs server
  service:
    name: nfsd
    state: restarted

