---
# Configure podman rootless containers

- name: Ensure podman is installed
  dnf:
    state: present
    pkg: "{{ item }}"
  loop:
    - podman
    - skopeo
    - buildah

- name: Configure subordinate UID/GID mapping
  template:
    src: "subordinate-map.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  loop:
    - subuid
    - subgid
  notify: podman migrate

- name: Configure max user namespaces
  sysctl:
    name: user.max_user_namespaces
    value: '100000'
    state: present
    sysctl_file: /etc/sysctl.d/75-user-namespaces.conf
    sysctl_set: yes
    reload: yes
