---

- name: Configure static IP on private interface
  lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^ifconfig_msk0="
    line: "ifconfig_msk0=\"inet 192.168.0.254 netmask 255.255.255.0\""
    validate: "sysrc -f %s -c ifconfig_msk0"
  notify:
    - Restart net interface

- name: Configure DHCP on public interface
  lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^ifconfig_msk1="
    line: "ifconfig_msk1=\"DHCP\""
    validate: "sysrc -f %s -c ifconfig_msk1"
  notify:
    - Restart net interface

- name: Configure DHCP client to preserve ns & search in resolv.conf
  copy:
    src: dhclient.conf
    dest: /etc/dhclient.conf
  notify:
    - Restart dhclient

- name: Configure default route
  lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^defaultrouter"
    line: "defaultrouter=\"192.168.1.254\""
    validate: "sysrc -f %s -c defaultrouter"
  notify:
    - Restart routing

- name: Configure IPv4 Forwarding
  lineinfile:
    path: /etc/rc.conf
    backup: yes
    regexp: "^gateway_enable"
    line: "gateway_enable=\"YES\""
    validate: "sysrc -f %s -c gateway_enable"
  notify:
    - Restart routing

