---

- name: Install ansible and dependencies (FreeBSD)
  pkgng:
    pkg: "{{ item }}"
    state: present
  loop:
    - sudo
    - git
    - python{{ freebsd_python_version }}
    - py{{ freebsd_python_version }}-ansible

