---
# Install ansible and dependencies

- name: Check if community.general collection is present
  stat:
    path: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/community/general"
  register: community_general_collection

- name: Install Community General collection
  command: ansible-galaxy collection install community.general
  when: not community_general_collection.stat.exists

- import_tasks: freebsd.yml
  when: community_general_collection.stat.exists

