---
# Install ansible and dependencies

- name: Check if community.general collection is present
  stat:
    path: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections/community/general"
  register: community_general_collection

- name: Install Community General collection
  command: ansible-galaxy collection install community.general
  when: not community_general_collection.stat.exists

- name: Install ansible and dependencies (FreeBSD)
  community.general.pkgng:
    pkg: "{{ item }}"
    state: present
  loop:
    - sudo
    - git
    - python{{ freebsd_python_version }}
    - py{{ freebsd_python_version }}-ansible-{{ freebsd_ansible_version }}

