---

- name: Ensure core tools are present
  apt:
    name:
      - zsh
      - git
      - fzf
      - golang
        # - rust-all # too old, use offline installer, system-wide: 
        # wget https://static.rust-lang.org/dist/rust-1.74.0-aarch64-unknown-linux-gnu.tar.gz
        # ./install.sh --prefix=/usr/local
      - nnn
      - neovim
      - tmux
      - build-essential
      - gh
      - default-jdk
      - podman
      - buildah
      - postgresql-client
      # sudo alternatives --config javac
    state: present

# sudo cargo install --force --root /usr/local bandwhich bat bottom git-delta diskonaut du-dust eza fd-find grex hyperfine ripgrep sd tokei xh xsv ytop
- name: Install core tools from cargo
  community.general.cargo:
    name:
      - bandwhich
      - bat
      # - broot
      - bottom
      - git-delta
      # - deno
      - diskonaut
      - du-dust
      - eza
      - fd-find
      # - gping
      - grex
      - hyperfine
      # - procs
      - ripgrep
      - sd
      - tokei
      - xh
      - xsv
      - ytop
    state: present
    path: /usr/local

- name: Ensure craig account is present
  user:
    name: craig
    comment: Craig Perry
    shell: "/bin/zsh"
    group: craig
    groups: sudo
    append: yes
    generate_ssh_key: yes

- name: Add Public SSH Keys from Github             
  authorized_key:                                   
    user: craig                                   
    state: present                                  
    key: "https://github.com/craigjperry2.keys"

- name: Allow "wheel" group to have passwordless sudo
  lineinfile:
    dest: "/etc/sudoers"
    state: present
    regexp: "^%sudo"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -f %s -c"

- name: Checkout my dotfiles
  git:
    repo: https://github.com/craigjperry2/dotfiles.git
    dest: /home/craig/Code/github.com/craigjperry2/dotfiles
    update: no
  become: true
  become_user: craig

- name: Checkout p10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/craig/Code/github.com/romkatv/powerlevel10k
    update: no
  become: true
  become_user: craig

- name: Link gitconfig
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/gitconfig
    dest: /home/craig/.gitconfig
    state: link
    force: yes
    owner: craig
    group: craig

- name: Link zshrc
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/zshrc
    dest: /home/craig/.zshrc
    state: link
    force: yes
    owner: craig
    group: craig

- name: Link tmux.conf
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/tmux.conf
    dest: /home/craig/.tmux.conf
    state: link
    force: yes
    owner: craig
    group: craig

- name: Link tmux.remote.conf
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/tmux.remote.conf
    dest: /home/craig/.tmux.remote.conf
    state: link
    force: yes
    owner: craig
    group: craig

- name: Config directory
  file:
    path: /home/craig/.config
    state: directory
    mode: 0755

- name: Link neovim init.vim
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/nvim
    dest: /home/craig/.config/nvim
    state: link
    force: yes
    owner: craig
    group: craig

