---

- name: Ensure craig account is present
  user:
    name: craig
    comment: Craig Perry
    shell: "{{ zsh_path }}"
    group: craig
    groups: wheel
    append: yes
    generate_ssh_key: yes

- name: Add Public SSH Keys from Github             
  authorized_key:                                   
    user: craig                                   
    state: present                                  
    key: "https://github.com/craigjperry2.keys"

- name: Allow "wheel" group to have passwordless sudo
  lineinfile:
    dest: "{{ sudoers_path }}"
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -f %s -c"

- name: Checkout my dotfiles
  git:
    repo: https://github.com/craigjperry2/dotfiles.git
    dest: /home/craig/Code/github.com/craigjperry2/dotfiles
  notify:
  - Fix Code Permissions

- name: Checkout p10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/craig/Code/github.com/romkatv/powerlevel10k
  notify:
  - Fix Code Permissions

- name: Link gitconfig
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/gitconfig
    dest: /home/craig/.gitconfig
    state: link
    owner: craig
    group: craig

- name: Link zshrc
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/zshrc
    dest: /home/craig/.zshrc
    state: link
    owner: craig
    group: craig

- name: Link tmux.conf
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/tmux.conf
    dest: /home/craig/.tmux.conf
    state: link
    owner: craig
    group: craig

- name: Link neovim init.vim
  file:
    src: /home/craig/Code/github.com/craigjperry2/dotfiles/dotfiles/init.vim
    dest: /home/craig/.config/nvim/init.vim
    state: link
    owner: craig
    group: craig

