---

- name: Setup /etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    backup: yes

- name: Install dnsmasq
  pkgng:
    pkg: dnsmasq
    state: present

- name: Configure Ad blocklists
  copy:
    src: dnsmasq.conf.d
    dest: "{{ dnsmasq_conf_root }}"

- name: Configure Ad host lists
  copy:
    src: hosts.d
    dest: "{{ dnsmasq_conf_root }}"

- name: Configure Local DNS Server
  copy:
    src: dnsmasq.conf
    dest: "{{ dnsmasq_conf_root }}/dnsmasq.conf"
    backup: yes
    # TODO: Unbelievably, ansible REQUIRES %s in the validate command (?!) AND dnsmasq rejects anything beyond --test as "junk found in command line"!
    # validate: "dnsmasq --test  # %s"
  notify:
    - Restart dnsmasq

- name: Enable dnsmasq
  lineinfile:
    dest: /etc/rc.conf
    backup: yes
    state: present
    regexp: "^dnsmasq_enable"
    line: "dnsmasq_enable=\"YES\""
    validate: "sysrc -f %s -c dnsmasq_enable"
  notify:
    - Start dnsmasq

