---

# Install (or maintain) ansible pull mode

- name: Create ansible user
  user:
    name: ansible
    system: yes
    create_home: yes
    generate_ssh_key: yes
    comment: 'Ansible Configuration Management'

- name: Add warning comment to ansible sudoers file
  lineinfile:
    path: /etc/sudoers.d/ansible
    state: present
    create: yes
    insertbefore: BOF
    regexp: '^#'
    line: '## Automatically Managed by Ansible, Manual Changes Will Be Lost!'

- name: Disable requiretty restriction on ansible user
  lineinfile: 
    path: /etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^Defaults'
    line: 'Defaults: ansible !requiretty'

- name: Allow ansible user full sudo privs
  lineinfile: 
    path: /etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^ansible'
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'

- name: Install ansible pull-mode crontab entry
  cron:
    name: "ansible pull"
    state: present
    user: ansible
    special_time: hourly
    job: "ansible-pull -U https://github.com/craigjperry2/home-network -i hosts > $HOME/ansible-pull.$$.cron.log 2>&1"
