---

- name: Create ansible user
  user:
    name: ansible
    system: yes
    generate_ssh_key: yes
    comment: 'Ansible Configuration Management'

- name: Get Public SSH Keys from Github
  authorized_key:
    user: ansible
    state: present
    key: "https://github.com/{{ github_user }}.keys"

- name: Add warning comment to ansible sudoers file
  lineinfile:
    path: "{{ ansible_sudoers_file }}"
    state: present
    create: yes
    mode: 0440
    regexp: '^#'
    line: '## Managed by Ansible, Manual Changes Will Be Lost!'

- name: Disable requiretty restriction on ansible user
  lineinfile:
    path: "{{ ansible_sudoers_file }}"
    state: present
    create: yes
    regexp: '^Defaults'
    line: 'Defaults: ansible !requiretty'

- name: Allow ansible user full sudo privs
  lineinfile:
    path: "{{ ansible_sudoers_file }}"
    state: present
    create: yes
    regexp: '^ansible'
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'

- name: Ensure logs dir is present
  file:
    path: /home/ansible/logs
    state: directory
    owner: ansible
    group: ansible

- name: Ensure cron is installed
  yum:
    pkg: "{{ item }}"
    state: present
  loop:
    - cronie
    - cronie-anacron
  when: ansible_os_family == "RedHat"

- name: Install ansible pull-mode crontab entry
  cron:
    name: "ansible pull"
    user: ansible
    special_time: hourly
    job: "ansible-pull -l {{ ansible_hostname }}.home.craigjperry.com -U https://github.com/craigjperry2/home-network > $HOME/logs/ansible-pull.$$.cron.log 2>&1"

