---

# Install (or maintain) ansible pull mode

- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    system: yes
    generate_ssh_key: yes
    comment: 'Ansible Configuration Management'

- name: Add warning comment to ansible sudoers file
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^#'
    line: '## Managed by Ansible, Manual Changes Will Be Lost!'

- name: Disable requiretty restriction on ansible user
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^Defaults'
    line: 'Defaults: ansible !requiretty'

- name: Allow ansible user full sudo privs
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^ansible'
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'

# - name: Install ansible pull-mode crontab entry
#   cron:
#     name: "ansible pull"
#     state: present
#     user: ansible
#     special_time: hourly
#     job: "ansible-pull -U https://github.com/craigjperry2/home-network -i hosts > $HOME/logs/ansible-pull.$$.cron.log 2>&1"
# 
