---

- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    system: yes
    generate_ssh_key: yes
    comment: 'Ansible Configuration Management'

- name: Get Public SSH Keys from Github
  authorized_key:
    user: ansible
    state: present
    key: "https://github.com/{{ github_user }}.keys"

- name: Add warning comment to ansible sudoers file
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    mode: 0440
    regexp: '^#'
    line: '## Managed by Ansible, Manual Changes Will Be Lost!'

- name: Disable requiretty restriction on ansible user
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^Defaults'
    line: 'Defaults: ansible !requiretty'

- name: Allow ansible user full sudo privs
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers.d/ansible
    state: present
    create: yes
    regexp: '^ansible'
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'

