# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).
{
  config,
  pkgs,
  inputs,
  unstable,
  modulesPath,
  ...
}: {
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
  ];

  # Enable the X11 windowing system.
  # services.xserver.enable = true;

  # Configure keymap in X11
  # services.xserver.xkb.layout = "us";
  # services.xserver.xkb.options = "eurosign:e,caps:escape";

  # Enable sound.
  # services.pulseaudio.enable = true;
  # OR
  # services.pipewire = {
  #   enable = true;
  #   pulse.enable = true;
  # };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.libinput.enable = true;

  users.users.craig = {
    uid = 501;
    extraGroups = ["wheel" "orbstack"];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/craig";
    homeMode = "700";
    useDefaultShell = true;
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWTevJ63ZnTe1ftAB8bUp9oUhPnWsEaMxZnNkw6BpOukFfnwVT9/QcMSXRtY5z1SBfmeIPS/x+Co5BM1rkQlnQ7iETlX68rQUjaCW/f1761hWxvvsG5uWvgarcZWKJorEL5wXSxe41l0IWzzNQaBReNZvN/QCQVDUTQaB5jXGO2rrIa7B4M+rL+oMDQYKVdN66xLKRn6vu0lSkPaTeecTsakQ0XNEnFieYNTyQRh9SAvW4IVZLQnLqZx8Q1MskFE7+uZ0qP5IZdTJWVhSF2j+LRkruOs0dV73JGXNpopunoqHSC+9cg6nS+etRiTnhweRlsvjHSftlsYTxXXnlAuRFSZ+WWIx/KbSbBGnXbJVGitAJVHb1wA4D6f2f2Iw6ngnhJRKZ63tZGqJUJj2v8kDbOp4BAZnGTS6bnqVuGL0Of6AfHbPm5bWn+x6B5NDvgwhbBrYmQn+UQFvP3Y+YZj7qbHohrBVzICNMJSKRDOs2w4DNM/4BZepqlzicX85gedk="
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRn7uRtz/cItl2cizdD+Rqre53R7CC7yqypaXxnqdtqhY1nyVX+4RrVbqoeV+8IoNU9WEngWOGHFSDBW4Sp3xOEvj678i7tzo1OhkDZi/PLrpnQpzopgiERE9aVwD4XTM9NbhX1ODzyy9Nae+rcsS47XmzrNlWc6yuWNMy4kvqfOp4EefYiVz8IQKiwi3vAIxjfhZtbTLkjNd8K7KgbFg3lROaC3ckjgbJn+RPLH2vy1nYOGulsyFwEEJGpd5Ar2clV7/8OcCOHEwXj+ouNCPrtrmQthpwu/D6+U78x//s3xHlCq3GorrfcoIOCfqMh62uDK/vSvn064ofi4hliQGjloZuTRTLJHxiFX0RBhKp9zHnAR/EkHgI06vcWKqLY4LGC7txvhlD371fiPtUdblR8ppy4DKXNrE/uuGEHiIffrb5KthNMlmq4C+2FBaueD31gIo3rn0p2P92MH6BiVPUC93wsxZulvua0nArHSNwXA5WcPjv43sdjrb+nJSxIhk="
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9pHorrpMijyrP4U8LMZ7oC/jFAr1me9GCNMCGjZG6eGLkLnNb58vQivTblr9JUgBHTbNHJ6TTdcNMjQICCLiQDWrtupa2HOokDEHyserwyCShGwFGEGwdprBs5r4MpRIRyoNqWlfx3IJswV8TmKReQhjShBR91OXfuikIw28A8E7Bh1qLAiDGAfAps1skmQ5aIbxBuDH/uGD0l0wQOhNVXrsQHvZSawTtthjpJ5gpURbjdZ4ZwLmLBHa4sm77/E5QGe9QFIGPoN4JZeUF5Onf1Yu4oebC2W96RRHxhfDYVmneKD7g+6IuILnIB7vVojy/1u0voaQVXVA5h7ozE/AJd+vAe8CBw0bwrmCTJtckqFyEs0+u+jN0cmu51lH+P+jjPc3REZDQKZNqZMsb1y/Zn2LJlv2dspvhi5CPVyXNr2kXXCfw2XISWT+at4vjtRHcPpQSJisq/MP81EO8JzuyXYKYcCMoH7HUkCSom0zmo1WylBPCQtXIHu75Eo8Rj+Bhocs0QHlaWyKuicjqnbWEiOHV2khQACVs9a5xTTSPpOLHNsOoCLzuFUvD9iq4moDAlI8paJaIqR6+HayeTDf6frsGWPnOwDXnG1E6Va54uRb2Rstp3aDp+ifMLSrAfF9Mh6EQky/m69b+gZucs3TtmrRfI6MVK2M4ZLkn4L28nw=="
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/London";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
            -----BEGIN CERTIFICATE-----
      MIICCzCCAbGgAwIBAgIPEb8OX7o4/YFd+5UUkNWlMAoGCCqGSM49BAMCMGYxHTAb
      BgNVBAoTFE9yYlN0YWNrIERldmVsb3BtZW50MR4wHAYDVQQLDBVDb250YWluZXJz
      ICYgU2VydmljZXMxJTAjBgNVBAMTHE9yYlN0YWNrIERldmVsb3BtZW50IFJvb3Qg
      Q0EwHhcNMjUxMTAyMTgyOTIwWhcNMzUxMTAyMTgyOTIwWjBmMR0wGwYDVQQKExRP
      cmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVycyAmIFNlcnZp
      Y2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290IENBMFkwEwYH
      KoZIzj0CAQYIKoZIzj0DAQcDQgAEr+hjx4GeN2sVTk0he8KmZYGpt15Q+r0andlh
      xDjz/8I4wdL2T7Z3qQpkQzDQ5aaJHClI4aRR5kfxpjg8TT2DK6NCMEAwDgYDVR0P
      AQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMNfeF/NY6iMeE99
      6ytdpU3sA5zFMAoGCCqGSM49BAMCA0gAMEUCIQDrP+nOVFVTXAfJV7Jo3r461zcF
      Xp/ai3sRMAGVkhEI1AIgEY//Wt6V7cPRIC2vfAVCsn2MnimMFyS/xLhlS0FCJsA=
      -----END CERTIFICATE-----

    ''
  ];

  programs.zsh.enable = true;

  environment.shells = with pkgs; [zsh];

  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [
    curl
    ghostty.terminfo
    htop
    neovim
    p7zip
    sysstat
    unzip
    zellij
    zip
  ];

  # services = {
  #   openssh.enable = true;
  # };

  nix.settings.experimental-features = ["nix-command" "flakes"];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "26.05"; # Did you read the comment?
}
