---

- name: Install wireguard
  dnf:
    pkg: "wireguard-tools"
    state: present

- name: Add wireguard firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 31489/udp
    permanent: true
    state: enabled

- name: Check if keypair exists
  stat:
    path: /etc/wireguard/privatekey
  register: keypair

- name: Generate keypair
  shell: "umask 0266 ; wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey"
  when: keypair.stat.exists == false

- name: Maintain wireguard config
  vars:
    private_key: "{{ lookup('file', '/etc/wireguard/privatekey') }}"
    r1_public_key: "wTnhdg3jdL0fJfYQBAI4V1WsJxvLoOim5PTTYHXqC1Q="
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: Start wireguard on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
