# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dummy";
    fsType = "ext4";
  };

  # Note: The original hardware-configuration.nix for r3 was missing from the repository.
  # Please replace this file with the actual hardware-configuration.nix generated for r3.
}
